### ISSUE TITLE
Colour WTF?

### ISSUE THREAD

**Issue by irenevlachou** [BabyLegz/BabyLegz.github.io#1]
@BabyLegz where is the colour font? you should use that! :)
and can you please upload your "xxxx.glyphs" file?

Ειρήνη

**Comment by BabyLegz** [comment]
Could you please please tell me once again where on github I should upload
it? Sorry I'm a dumbass. And something is not okay with my color font (it's
not exporting) and I don't know why (I changed it again actually..)

Спасибо

pt., 6 mar 2020 o 00:48 Irene Vlachou <notifications@github.com> napisał(a):

**Comment by BabyLegz** [comment]
nevermind I fixed it :)

pt., 6 mar 2020 o 01:24 Viktoriia Kovalenko <s19140@pjwstk.edu.pl>
napisał(a):
